Repository pubnub/rust, pull requests merged in 2023-08, with the labels that each got.

#165 Add `@parfeon` as code owner
  .github/CODEOWNERS
Labels: priority: medium, status: done, type: chore

#167 Rename `set_state` to `set_presence_state`
  src/core/event_engine/transition.rs
  src/dx/presence/builders/mod.rs
  src/dx/presence/builders/set_presence_state.rs
  src/dx/presence/mod.rs
  src/dx/subscribe/builders/subscription.rs
  src/dx/subscribe/event_engine/effects/emit_messages.rs
  src/dx/subscribe/event_engine/types.rs
  src/dx/subscribe/mod.rs
  src/dx/subscribe/result.rs
  src/dx/subscribe/subscription_manager.rs
  src/dx/subscribe/types.rs
  tests/subscribe/subscribe_steps.rs
Labels: priority: medium, status: done, type: refactor

#168 add here_now to presence API
  Cargo.toml
  examples/here_now.rs
  examples/here_now_blocking.rs
  examples/presence_state.rs
  examples/presence_state_blocking.rs
  examples/where_now.rs
  examples/where_now_blocking.rs
  src/core/service_response.rs
  src/core/transport_request.rs
  src/dx/presence/builders/here_now.rs
  src/dx/presence/builders/mod.rs
  src/dx/presence/mod.rs
  src/dx/presence/result.rs
Labels: priority: high, type: feature

#169 where now presence API
  examples/where_now.rs
  examples/where_now_blocking.rs
  src/dx/presence/builders/mod.rs
  src/dx/presence/builders/where_now.rs
  src/dx/presence/mod.rs
  src/dx/presence/result.rs
Labels: priority: high, type: feature

#171 add get_presence_state to presence API
  examples/presence_state.rs
  examples/presence_state_blocking.rs
  src/dx/presence/builders/get_presence_state.rs
  src/dx/presence/builders/mod.rs
  src/dx/presence/mod.rs
  src/dx/presence/result.rs
Labels: priority: high, type: feature

#170 Subscribe EE works with presence EE
  examples/subscribe.rs
  src/core/error.rs
  src/dx/presence/builders/heartbeat.rs
  src/dx/presence/mod.rs
  src/dx/presence/presence_manager.rs
  src/dx/pubnub_client.rs
  src/dx/subscribe/builders/raw.rs
  src/dx/subscribe/builders/subscribe.rs
  src/dx/subscribe/builders/subscription.rs
  src/dx/subscribe/event_engine/effects/handshake.rs
  src/dx/subscribe/event_engine/effects/handshake_reconnection.rs
  src/dx/subscribe/event_engine/effects/receive.rs
  src/dx/subscribe/event_engine/effects/receive_reconnection.rs
  src/dx/subscribe/event_engine/types.rs
  src/dx/subscribe/mod.rs
  src/dx/subscribe/subscription_manager.rs
Labels: priority: high, status: done, type: feature
